project_name: "cloud_engineer_portfolio"
vpc_cidr: "172.16.0.0/16"
public_subnets: ["172.16.0.0/24", "172.16.1.0/24"]
private_subnets: ["172.16.2.0/24", "172.16.3.0/24"]
azs: ["us-east-1a", "us-east-1b"]
owner: "doug"
